version: 2.1

jobs:
  test:
    docker:
      - image: python:3.9
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-deps-{{ checksum "poetry.lock" }}
            - v1-deps
      - run: pip install -U poetry
      - save_cache:
          key: v1-deps-{{ checksum "poetry.lock" }}
          paths:
            - /home/circleci/.cache/pypoetry/virtualenvs
      - run: make test.ci

workflows:
  build_and_test:
    jobs:
      - test
